"""a sitting's last activity

Revision: 9bb6abb1a049
Revises: 6f53c84ec86a
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9bb6abb1a049"
down_revision: str | Sequence[str] | None = "6f53c84ec86a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sittings", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sittings", "last_active_at")
    # ### end Alembic commands ###
