"""every table

Revision: 774cdb316fc3
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "774cdb316fc3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# the enum types, created once before any table and dropped after every one.
# A column created with a type of its own would create it again on the next
# table that uses it, and a downgrade would leave it behind
PROBLEM_DIFFICULTY = postgresql.ENUM(
    "easy", "medium", "hard", name="problem_difficulty", create_type=False
)
TEMPLATE_KIND = postgresql.ENUM("code", "procedure", name="template_kind", create_type=False)
PROBLEM_STATUS = postgresql.ENUM("created", "retired", name="problem_status", create_type=False)
RETIREMENT_REASON = postgresql.ENUM("defective", name="retirement_reason", create_type=False)
GATE = postgresql.ENUM(
    "no_value",
    "misdeclared",
    "untested",
    "disagreed",
    "unexercised",
    name="gate",
    create_type=False,
)
CALL_SITE = postgresql.ENUM(
    "generator", "blind", "discrimination", "inputs", "naive", name="call_site", create_type=False
)
SOLUTION_ROLE = postgresql.ENUM(
    "canonical", "reference", "naive", name="solution_role", create_type=False
)
EXPECTED_SOURCE = postgresql.ENUM(
    "reference", "canonical", name="expected_source", create_type=False
)
SETTLED_FIELD = postgresql.ENUM(
    "cases", "kept", "won", "separating_case", name="settled_field", create_type=False
)
CLAIM_SOURCE = postgresql.ENUM("user", "classifier", name="claim_source", create_type=False)
MATCH_SOURCE = postgresql.ENUM(
    "user", "generator", "classifier", name="match_source", create_type=False
)
CONFIDENCE = postgresql.ENUM("guess", "leaning", "sure", name="confidence", create_type=False)
FAILURE_MODE = postgresql.ENUM(
    "speed", "rust", "gap", "syntax", "none", name="failure_mode", create_type=False
)
CASE_OUTCOME = postgresql.ENUM(
    "passed", "wrong", "timeout", "crashed", name="case_outcome", create_type=False
)
WRITING_STATE = postgresql.ENUM(
    "drafted",
    "checked",
    "referenced",
    "agreed",
    "built",
    "paced",
    "searched",
    "hardened",
    "landed",
    "rejected",
    name="writing_state",
    create_type=False,
)
TYPES = (
    WRITING_STATE,
    PROBLEM_DIFFICULTY,
    TEMPLATE_KIND,
    PROBLEM_STATUS,
    RETIREMENT_REASON,
    GATE,
    CALL_SITE,
    SOLUTION_ROLE,
    EXPECTED_SOURCE,
    SETTLED_FIELD,
    CLAIM_SOURCE,
    MATCH_SOURCE,
    CONFIDENCE,
    FAILURE_MODE,
    CASE_OUTCOME,
)


def upgrade() -> None:
    for kind in TYPES:
        kind.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("effort", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("prompt_hash", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("pin", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Double(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("requests", sa.Integer(), nullable=True),
        sa.Column("request_ms", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "prompt <> '' AND prompt_hash <> ''", name=op.f("calls_prompt_named_check")
        ),
        sa.CheckConstraint(
            "(response IS NULL) <> (error IS NULL)", name=op.f("calls_answered_or_failed_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("calls_pkey")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("technique", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("selector_technique", sa.Text(), nullable=False),
        sa.Column(
            "selector_difficulty",
            postgresql.ARRAY(PROBLEM_DIFFICULTY),
            nullable=False,
        ),
        sa.Column("selector_size", sa.Integer(), nullable=False),
        sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9-]*$'", name=op.f("cards_slug_spelled_check")),
        sa.CheckConstraint(
            "trigger <> '' AND brief <> ''", name=op.f("cards_trigger_and_brief_written_check")
        ),
        sa.CheckConstraint("selector_size >= 1", name=op.f("cards_ladder_of_something_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("cards_pkey")),
        sa.UniqueConstraint("slug", name=op.f("cards_slug_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id <> ''", name=op.f("users_id_minted_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_table(
        "card_templates",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("card_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("speedup", sa.Boolean(), nullable=False),
        sa.Column("kind", TEMPLATE_KIND, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]*$'", name=op.f("card_templates_slug_spelled_check")
        ),
        sa.CheckConstraint("trigger <> ''", name=op.f("card_templates_trigger_written_check")),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("card_templates_card_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("card_templates_pkey")),
        sa.UniqueConstraint(
            "card_id", "position", name=op.f("card_templates_card_id_position_key")
        ),
        sa.UniqueConstraint("card_id", "slug", name=op.f("card_templates_card_id_slug_key")),
    )
    op.create_index(
        "card_templates_one_optional_idx",
        "card_templates",
        ["card_id"],
        unique=True,
        postgresql_where=sa.text("optional"),
    )
    op.create_table(
        "problems",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            PROBLEM_DIFFICULTY,
            nullable=True,
        ),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("target_template_id", sa.Text(), nullable=True),
        sa.Column("target_technique", sa.Text(), nullable=True),
        sa.Column("status", PROBLEM_STATUS, nullable=False),
        sa.Column("retired_reason", RETIREMENT_REASON, nullable=True),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(status = 'retired') = (retired_reason IS NOT NULL)",
            name=op.f("problems_retirement_names_its_reason_check"),
        ),
        sa.CheckConstraint("statement <> ''", name=op.f("problems_statement_written_check")),
        sa.CheckConstraint(
            "target_template_id <> '' AND target_technique <> ''",
            name=op.f("problems_target_named_check"),
        ),
        sa.CheckConstraint(
            "target_template_id IS NULL OR target_technique IS NULL",
            name=op.f("problems_one_target_check"),
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], name=op.f("problems_call_id_fkey")),
        sa.ForeignKeyConstraint(
            ["target_template_id"],
            ["card_templates.id"],
            name=op.f("problems_target_template_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("problems_pkey")),
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "state",
            WRITING_STATE,
            nullable=False,
        ),
        sa.Column(
            "gate",
            GATE,
            nullable=True,
        ),
        sa.Column("problem_id", sa.Text(), nullable=True),
        sa.Column("target_template_id", sa.Text(), nullable=True),
        sa.Column("target_technique", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            PROBLEM_DIFFICULTY,
            nullable=False,
        ),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("input_generator", sa.Text(), nullable=True),
        sa.Column("largest", sa.Integer(), nullable=True),
        sa.Column("naive", sa.Text(), nullable=True),
        sa.Column("unseparated", sa.Text(), nullable=True),
        sa.Column("ceiling", sa.Integer(), nullable=True),
        sa.Column("margin", sa.Integer(), nullable=True),
        sa.Column("repeats_max", sa.Integer(), nullable=True),
        sa.Column("search_revision", sa.Integer(), nullable=True),
        sa.Column("generator_call_id", sa.Text(), nullable=True),
        sa.Column("blind_call_id", sa.Text(), nullable=True),
        sa.Column("inputs_call_id", sa.Text(), nullable=True),
        sa.Column("naive_call_id", sa.Text(), nullable=True),
        sa.Column("discrimination_call_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(state = 'landed') = (problem_id IS NOT NULL)",
            name=op.f("drafts_landing_names_the_problem_check"),
        ),
        sa.CheckConstraint(
            "(state = 'rejected') = (gate IS NOT NULL)",
            name=op.f("drafts_rejection_names_its_gate_check"),
        ),
        sa.CheckConstraint(
            "id <> '' AND title <> '' AND statement <> '' AND canonical <> ''",
            name=op.f("drafts_drafted_written_check"),
        ),
        sa.CheckConstraint(
            "reference <> '' AND input_generator <> '' AND naive <> '' AND unseparated <> ''",
            name=op.f("drafts_later_steps_written_check"),
        ),
        sa.CheckConstraint(
            "target_template_id <> '' AND target_technique <> ''",
            name=op.f("drafts_target_named_check"),
        ),
        sa.CheckConstraint(
            "(input_generator IS NULL) = (largest IS NULL)",
            name=op.f("drafts_input_generator_carries_its_bound_check"),
        ),
        sa.CheckConstraint(
            "largest > 0 AND ceiling > 0 AND margin > 0 AND repeats_max > 0"
            " AND search_revision > 0",
            name=op.f("drafts_bounds_positive_check"),
        ),
        sa.CheckConstraint(
            "target_template_id IS NULL OR target_technique IS NULL",
            name=op.f("drafts_one_target_check"),
        ),
        sa.ForeignKeyConstraint(
            ["blind_call_id"], ["calls.id"], name=op.f("drafts_blind_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["discrimination_call_id"],
            ["calls.id"],
            name=op.f("drafts_discrimination_call_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["generator_call_id"], ["calls.id"], name=op.f("drafts_generator_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["inputs_call_id"], ["calls.id"], name=op.f("drafts_inputs_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["naive_call_id"], ["calls.id"], name=op.f("drafts_naive_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("drafts_problem_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["target_template_id"],
            ["card_templates.id"],
            name=op.f("drafts_target_template_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("drafts_pkey")),
    )
    op.create_table(
        "site_outcomes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "site",
            CALL_SITE,
            nullable=False,
        ),
        sa.Column("writing_id", sa.Text(), nullable=False),
        sa.Column("target_template_id", sa.Text(), nullable=True),
        sa.Column("target_technique", sa.Text(), nullable=True),
        sa.Column("problem_id", sa.Text(), nullable=True),
        sa.Column(
            "gate",
            GATE,
            nullable=True,
        ),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("mutants", sa.Integer(), nullable=False),
        sa.Column("survived", sa.Integer(), nullable=False),
        sa.Column("won", sa.Integer(), nullable=False),
        sa.Column("killed", sa.Integer(), nullable=False),
        sa.Column("rounds", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("proposed", sa.Integer(), nullable=False),
        sa.Column("misdeclared", sa.Integer(), nullable=False),
        sa.Column("separating", sa.Integer(), nullable=True),
        sa.Column("repeats", sa.Integer(), nullable=False),
        sa.Column("unseparated", sa.Text(), nullable=True),
        sa.Column("largest", sa.Integer(), nullable=True),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "target_template_id <> '' AND target_technique <> ''",
            name=op.f("site_outcomes_target_named_check"),
        ),
        sa.CheckConstraint("writing_id <> ''", name=op.f("site_outcomes_writing_named_check")),
        sa.CheckConstraint("largest > 0", name=op.f("site_outcomes_bound_positive_check")),
        sa.CheckConstraint("repeats >= 1", name=op.f("site_outcomes_called_at_least_once_check")),
        sa.CheckConstraint(
            "target_template_id IS NULL OR target_technique IS NULL",
            name=op.f("site_outcomes_one_target_check"),
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], name=op.f("site_outcomes_call_id_fkey")),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("site_outcomes_problem_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["target_template_id"],
            ["card_templates.id"],
            name=op.f("site_outcomes_target_template_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("site_outcomes_pkey")),
    )
    op.create_index(
        op.f("site_outcomes_writing_id_idx"), "site_outcomes", ["writing_id"], unique=False
    )
    op.create_table(
        "sittings",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("problem_id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at >= started_at", name=op.f("sittings_ends_after_it_starts_check")
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("sittings_problem_id_fkey")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("sittings_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("sittings_pkey")),
    )
    op.create_index(
        "sittings_one_running_idx",
        "sittings",
        ["user_id", "problem_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "solutions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("problem_id", sa.Text(), nullable=False),
        sa.Column("role", SOLUTION_ROLE, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.CheckConstraint("code <> ''", name=op.f("solutions_code_written_check")),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], name=op.f("solutions_call_id_fkey")),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("solutions_problem_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("solutions_pkey")),
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("problem_id", sa.Text(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "expected_from",
            EXPECTED_SOURCE,
            nullable=False,
        ),
        sa.Column("round", sa.Integer(), nullable=True),
        sa.Column("repeats", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(args) = 'array'", name=op.f("test_cases_args_positional_check")
        ),
        sa.CheckConstraint("repeats >= 1", name=op.f("test_cases_called_at_least_once_check")),
        sa.CheckConstraint("round >= 0", name=op.f("test_cases_round_counted_check")),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], name=op.f("test_cases_call_id_fkey")),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("test_cases_problem_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("test_cases_pkey")),
    )
    op.create_index(op.f("test_cases_problem_id_idx"), "test_cases", ["problem_id"], unique=False)
    op.create_table(
        "attempts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("problem_id", sa.Text(), nullable=False),
        sa.Column("sitting_id", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("time_to_solve_sec", sa.Double(), nullable=True),
        sa.Column("solved", sa.Boolean(), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.CheckConstraint("time_to_solve_sec >= 0", name=op.f("attempts_time_counted_check")),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems.id"], name=op.f("attempts_problem_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sitting_id"], ["sittings.id"], name=op.f("attempts_sitting_id_fkey")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("attempts_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("attempts_pkey")),
    )
    op.create_index(op.f("attempts_sitting_id_idx"), "attempts", ["sitting_id"], unique=False)
    op.create_index(op.f("attempts_user_id_idx"), "attempts", ["user_id"], unique=False)
    op.create_table(
        "draft_declared_cases",
        sa.Column("draft_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(args) = 'array'", name=op.f("draft_declared_cases_args_positional_check")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
            name=op.f("draft_declared_cases_draft_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("draft_id", "position", name=op.f("draft_declared_cases_pkey")),
    )
    op.create_table(
        "draft_settled_cases",
        sa.Column("draft_id", sa.Text(), nullable=False),
        sa.Column(
            "draft_field",
            SETTLED_FIELD,
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "expected_from",
            EXPECTED_SOURCE,
            nullable=False,
        ),
        sa.Column("round", sa.Integer(), nullable=True),
        sa.Column("repeats", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "draft_field <> 'separating_case' OR position = 0",
            name=op.f("draft_settled_cases_one_separating_case_check"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(args) = 'array'", name=op.f("draft_settled_cases_args_positional_check")
        ),
        sa.CheckConstraint(
            "repeats >= 1", name=op.f("draft_settled_cases_called_at_least_once_check")
        ),
        sa.CheckConstraint("round >= 0", name=op.f("draft_settled_cases_round_counted_check")),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("draft_settled_cases_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
            name=op.f("draft_settled_cases_draft_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "draft_id", "draft_field", "position", name=op.f("draft_settled_cases_pkey")
        ),
    )
    op.create_table(
        "sitting_pauses",
        sa.Column("sitting_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "until >= at", name=op.f("sitting_pauses_ends_no_earlier_than_it_starts_check")
        ),
        sa.ForeignKeyConstraint(
            ["sitting_id"], ["sittings.id"], name=op.f("sitting_pauses_sitting_id_fkey")
        ),
        sa.PrimaryKeyConstraint("sitting_id", "position", name=op.f("sitting_pauses_pkey")),
    )
    op.create_table(
        "solution_claims",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("solution_id", sa.Text(), nullable=False),
        sa.Column("techniques", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source", CLAIM_SOURCE, nullable=False),
        sa.Column("informed_by", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(source = 'classifier') = (call_id IS NOT NULL)",
            name=op.f("solution_claims_call_matches_source_check"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("solution_claims_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"], ["solutions.id"], name=op.f("solution_claims_solution_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("solution_claims_pkey")),
    )
    op.create_table(
        "template_matches",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("template_id", sa.Text(), nullable=False),
        sa.Column("solution_id", sa.Text(), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            MATCH_SOURCE,
            nullable=False,
        ),
        sa.Column("informed_by", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(source = 'classifier') = (call_id IS NOT NULL)",
            name=op.f("template_matches_call_matches_source_check"),
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("template_matches_call_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"], ["solutions.id"], name=op.f("template_matches_solution_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["card_templates.id"], name=op.f("template_matches_template_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("template_matches_pkey")),
    )
    op.create_table(
        "verifications",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("solution_id", sa.Text(), nullable=False),
        sa.Column("cap_ms", sa.Integer(), nullable=False),
        sa.Column("runner", sa.Text(), nullable=False),
        sa.CheckConstraint("runner <> ''", name=op.f("verifications_runner_named_check")),
        sa.CheckConstraint("cap_ms > 0", name=op.f("verifications_capped_check")),
        sa.ForeignKeyConstraint(
            ["solution_id"], ["solutions.id"], name=op.f("verifications_solution_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("verifications_pkey")),
    )
    op.create_index(
        op.f("verifications_solution_id_idx"), "verifications", ["solution_id"], unique=False
    )
    op.create_table(
        "attempt_claims",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("techniques", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("declined", sa.Boolean(), nullable=False),
        sa.Column("source", CLAIM_SOURCE, nullable=False),
        sa.Column("informed_by", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("confidence", CONFIDENCE, nullable=True),
        sa.Column("call_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(source = 'classifier') = (call_id IS NOT NULL)",
            name=op.f("attempt_claims_call_matches_source_check"),
        ),
        sa.CheckConstraint(
            "source <> 'user' OR cardinality(techniques) > 0 OR declined",
            name=op.f("attempt_claims_user_claim_answers_check"),
        ),
        sa.CheckConstraint(
            "NOT (cardinality(techniques) > 0 AND declined)",
            name=op.f("attempt_claims_decline_names_nothing_check"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("attempt_claims_attempt_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("attempt_claims_call_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("attempt_claims_pkey")),
    )
    op.create_index(
        op.f("attempt_claims_attempt_id_idx"), "attempt_claims", ["attempt_id"], unique=False
    )
    op.create_table(
        "attempt_verifications",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("cap_ms", sa.Integer(), nullable=False),
        sa.Column("runner", sa.Text(), nullable=False),
        sa.CheckConstraint("runner <> ''", name=op.f("attempt_verifications_runner_named_check")),
        sa.CheckConstraint("cap_ms > 0", name=op.f("attempt_verifications_capped_check")),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("attempt_verifications_attempt_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("attempt_verifications_pkey")),
    )
    op.create_index(
        op.f("attempt_verifications_attempt_id_idx"),
        "attempt_verifications",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "diagnoses",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column(
            "mode",
            FAILURE_MODE,
            nullable=False,
        ),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("diagnoses_attempt_id_fkey")
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], name=op.f("diagnoses_call_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("diagnoses_pkey")),
    )
    op.create_index(op.f("diagnoses_attempt_id_idx"), "diagnoses", ["attempt_id"], unique=False)
    op.create_table(
        "self_labels",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column(
            "mode",
            FAILURE_MODE,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("self_labels_attempt_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("self_labels_pkey")),
    )
    op.create_index(op.f("self_labels_attempt_id_idx"), "self_labels", ["attempt_id"], unique=False)
    op.create_table(
        "verification_case_results",
        sa.Column("verification_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column(
            "outcome",
            CASE_OUTCOME,
            nullable=False,
        ),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "error IS NULL OR outcome = 'crashed'",
            name=op.f("verification_case_results_only_a_crash_names_an_error_check"),
        ),
        sa.CheckConstraint(
            "outcome NOT IN ('passed', 'wrong') OR elapsed_ms IS NOT NULL",
            name=op.f("verification_case_results_returned_was_timed_check"),
        ),
        sa.CheckConstraint(
            "elapsed_ms >= 0", name=op.f("verification_case_results_elapsed_counted_check")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["test_cases.id"], name=op.f("verification_case_results_case_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verifications.id"],
            name=op.f("verification_case_results_verification_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "verification_id", "position", name=op.f("verification_case_results_pkey")
        ),
    )
    op.create_table(
        "attempt_verification_case_results",
        sa.Column("attempt_verification_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column(
            "outcome",
            CASE_OUTCOME,
            nullable=False,
        ),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "error IS NULL OR outcome = 'crashed'",
            name=op.f("attempt_verification_case_results_only_a_crash_names_an_error_check"),
        ),
        sa.CheckConstraint(
            "outcome NOT IN ('passed', 'wrong') OR elapsed_ms IS NOT NULL",
            name=op.f("attempt_verification_case_results_returned_was_timed_check"),
        ),
        sa.CheckConstraint(
            "elapsed_ms >= 0", name=op.f("attempt_verification_case_results_elapsed_counted_check")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_verification_id"],
            ["attempt_verifications.id"],
            name=op.f("attempt_verification_case_results_attempt_verification_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
            name=op.f("attempt_verification_case_results_case_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "attempt_verification_id",
            "position",
            name=op.f("attempt_verification_case_results_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attempt_verification_case_results")
    op.drop_table("verification_case_results")
    op.drop_index(op.f("self_labels_attempt_id_idx"), table_name="self_labels")
    op.drop_table("self_labels")
    op.drop_index(op.f("diagnoses_attempt_id_idx"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index(op.f("attempt_verifications_attempt_id_idx"), table_name="attempt_verifications")
    op.drop_table("attempt_verifications")
    op.drop_index(op.f("attempt_claims_attempt_id_idx"), table_name="attempt_claims")
    op.drop_table("attempt_claims")
    op.drop_index(op.f("verifications_solution_id_idx"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_table("template_matches")
    op.drop_table("solution_claims")
    op.drop_table("sitting_pauses")
    op.drop_table("draft_settled_cases")
    op.drop_table("draft_declared_cases")
    op.drop_index(op.f("attempts_user_id_idx"), table_name="attempts")
    op.drop_index(op.f("attempts_sitting_id_idx"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(op.f("test_cases_problem_id_idx"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_table("solutions")
    op.drop_index(
        "sittings_one_running_idx",
        table_name="sittings",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("sittings")
    op.drop_index(op.f("site_outcomes_writing_id_idx"), table_name="site_outcomes")
    op.drop_table("site_outcomes")
    op.drop_table("drafts")
    op.drop_table("problems")
    op.drop_index(
        "card_templates_one_optional_idx",
        table_name="card_templates",
        postgresql_where=sa.text("optional"),
    )
    op.drop_table("card_templates")
    op.drop_table("users")
    op.drop_table("cards")
    op.drop_table("calls")
    # ### end Alembic commands ###
    for kind in TYPES:
        kind.drop(op.get_bind(), checkfirst=True)
