"""appended order

Revision: 24d3fa6eee53
Revises: 774cdb316fc3
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "24d3fa6eee53"
down_revision: str | Sequence[str] | None = "774cdb316fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # a row already in a table takes its number in the order Postgres scans the
    # table, which is not the order it landed in: copy the logs in again
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attempt_claims",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("attempt_claims_appended_key"), "attempt_claims", ["appended"])
    op.add_column(
        "attempt_verifications",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(
        op.f("attempt_verifications_appended_key"), "attempt_verifications", ["appended"]
    )
    op.add_column(
        "attempts", sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False)
    )
    op.create_unique_constraint(op.f("attempts_appended_key"), "attempts", ["appended"])
    op.add_column(
        "calls", sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False)
    )
    op.create_unique_constraint(op.f("calls_appended_key"), "calls", ["appended"])
    op.add_column(
        "diagnoses",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("diagnoses_appended_key"), "diagnoses", ["appended"])
    op.add_column(
        "self_labels",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("self_labels_appended_key"), "self_labels", ["appended"])
    op.add_column(
        "site_outcomes",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("site_outcomes_appended_key"), "site_outcomes", ["appended"])
    op.add_column(
        "solution_claims",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(
        op.f("solution_claims_appended_key"), "solution_claims", ["appended"]
    )
    op.add_column(
        "solutions",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("solutions_appended_key"), "solutions", ["appended"])
    op.add_column(
        "template_matches",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(
        op.f("template_matches_appended_key"), "template_matches", ["appended"]
    )
    op.add_column(
        "test_cases",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("test_cases_appended_key"), "test_cases", ["appended"])
    op.add_column(
        "verifications",
        sa.Column("appended", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(op.f("verifications_appended_key"), "verifications", ["appended"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("verifications_appended_key"), "verifications", type_="unique")
    op.drop_column("verifications", "appended")
    op.drop_constraint(op.f("test_cases_appended_key"), "test_cases", type_="unique")
    op.drop_column("test_cases", "appended")
    op.drop_constraint(op.f("template_matches_appended_key"), "template_matches", type_="unique")
    op.drop_column("template_matches", "appended")
    op.drop_constraint(op.f("solutions_appended_key"), "solutions", type_="unique")
    op.drop_column("solutions", "appended")
    op.drop_constraint(op.f("solution_claims_appended_key"), "solution_claims", type_="unique")
    op.drop_column("solution_claims", "appended")
    op.drop_constraint(op.f("site_outcomes_appended_key"), "site_outcomes", type_="unique")
    op.drop_column("site_outcomes", "appended")
    op.drop_constraint(op.f("self_labels_appended_key"), "self_labels", type_="unique")
    op.drop_column("self_labels", "appended")
    op.drop_constraint(op.f("diagnoses_appended_key"), "diagnoses", type_="unique")
    op.drop_column("diagnoses", "appended")
    op.drop_constraint(op.f("calls_appended_key"), "calls", type_="unique")
    op.drop_column("calls", "appended")
    op.drop_constraint(op.f("attempts_appended_key"), "attempts", type_="unique")
    op.drop_column("attempts", "appended")
    op.drop_constraint(
        op.f("attempt_verifications_appended_key"), "attempt_verifications", type_="unique"
    )
    op.drop_column("attempt_verifications", "appended")
    op.drop_constraint(op.f("attempt_claims_appended_key"), "attempt_claims", type_="unique")
    op.drop_column("attempt_claims", "appended")
    # ### end Alembic commands ###
